//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacionsalas
    {
        public int idasignacionsalas { get; set; }
        public Nullable<int> fkidparticipacion { get; set; }
        public Nullable<int> fkidsalacompetencia { get; set; }
    
        public virtual participacion participacion { get; set; }
        public virtual salacompetencia salacompetencia { get; set; }
    }
}
