//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class competencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public competencia()
        {
            this.grupo = new HashSet<grupo>();
            this.salacompetencia = new HashSet<salacompetencia>();
            this.correoCompetencia = new HashSet<correoCompetencia>();
            this.participacion = new HashSet<participacion>();
        }
    
        public int idcompetencia { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cupos { get; set; }
        public Nullable<System.DateTime> fechacompetencia { get; set; }
        public Nullable<System.TimeSpan> hotainicio { get; set; }
        public Nullable<System.TimeSpan> horafin { get; set; }
        public Nullable<int> cantidadejercicios { get; set; }
        public Nullable<int> numeroparticipantes { get; set; }
        public Nullable<System.DateTime> limiteinscripcion { get; set; }
        public Nullable<int> fkestado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo> grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salacompetencia> salacompetencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<correoCompetencia> correoCompetencia { get; set; }
        public virtual estadocompetencia estadocompetencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participacion> participacion { get; set; }
    }
}
