//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correoCompetencia
    {
        public int idcorreoCompetencia { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> fkidcompetencia { get; set; }
    
        public virtual competencia competencia { get; set; }
    }
}
