//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participacion()
        {
            this.asignacionsalas = new HashSet<asignacionsalas>();
        }
    
        public int idparticipacion { get; set; }
        public Nullable<int> fkidgrupo { get; set; }
        public Nullable<int> fkidnivel { get; set; }
        public Nullable<int> fkidcompetencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacionsalas> asignacionsalas { get; set; }
        public virtual competencia competencia { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual nivel nivel { get; set; }
    }
}
