//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilegio
    {
        public int idprivilegio { get; set; }
        public Nullable<int> fkestadoprivilegio { get; set; }
        public Nullable<int> fkrol { get; set; }
        public Nullable<int> fkmenu { get; set; }
    
        public virtual estadoprivilegio estadoprivilegio { get; set; }
        public virtual menu menu { get; set; }
        public virtual rol rol { get; set; }
    }
}
