//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salacompetencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salacompetencia()
        {
            this.asignacionsalas = new HashSet<asignacionsalas>();
        }
    
        public int idsalacompetencia { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cupos { get; set; }
        public Nullable<int> fkidcompetencia { get; set; }
        public Nullable<int> fkidsala { get; set; }
        public Nullable<int> fkestado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacionsalas> asignacionsalas { get; set; }
        public virtual competencia competencia { get; set; }
        public virtual estadosalacompetencia estadosalacompetencia { get; set; }
        public virtual sala sala { get; set; }
    }
}
