//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semillero_ProgramacioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idusuario { get; set; }
        public string correoelectronico { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> fkidepersona { get; set; }
        public Nullable<int> fkrol { get; set; }
        public Nullable<int> fkestado { get; set; }
    
        public virtual estadousuario estadousuario { get; set; }
        public virtual persona persona { get; set; }
        public virtual rol rol { get; set; }
    }
}
